### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by ghost** [FREEZX/fq777-954-chrome-app#1]
I know it's in development and I really appreciate that you already released what you have, but a short instruction how to setup things would be awesome.
Keep up the work. :+1: 

btw: This app should work cross platform (windows, linux, os x) in chrome browsers, right?

**Comment by FREEZX** [comment]
Yup, it should work cross-platform, no problem.
It should also be fairly easy to port to android and ios via cordova.
To set up, first just follow the standard chrome app tutorial (load chrome app from folder).

**Comment by ghost** [comment]
Sorry. I wasn't clear about the steps that are missing for me.
I already had the extension installed, but when launching it a window pops up which has a small black box in it. Thats all.
I have a Sixaxis PS3 controller on Linux (tested with jstest-gtk).

The extension does at least do something. If I open it and am connected to the FQ777 the binding LEDs stop flashing. But moving the PS3 controller sticks seems to do nothing.

**Comment by ghost** [comment]
I found the error logs:
![screenshot from 2016-03-28 17 58 53](https://cloud.githubusercontent.com/assets/9747396/14082258/4885ba22-f50f-11e5-869a-1804e0e765f9.png)

**Comment by ghost** [comment]
Trying it on Win10 did work now.
Did you bind button R2 to throttle on purpose?
I'd even rather hold down left stick before start.

btw:
It should be fairly easy to implement a "safe mode" switch like on bigger quadcopters that toggles command send on and off. You then can have throttle on left stick and make for example L2 button start / stop flight command transmission. You would not have to hold down the throttle stick. Just stop transmission after flight and its safe.

EDIT: forgot to mention that I use xbox 360 gamepad layout

**Comment by FREEZX** [comment]
Yep, i felt like i have more control of the throttle with R2 without it affecting the rotation of the drone, but now i think it might be better to have R2 increase throttle and L2 to decrease the throttle.
I'm not sure what happens when the drone stops receiving data, but i think it's a good idea to have the safe mode (maybe start button on the gamepad).

**Comment by ghost** [comment]
My friend has a flight controller joystick for PC. I'd love to try flying with that!
Would it be difficult to rebind the buttons and sticks? (might have to deal with inverted values)
I didn't figure out yet what exactly needs to be changed to make the stick instead of R2 control the throttle.

I actually have another idea for the script. Sorry for only bringing them up, but not being able to implement them :D

My idea:
The user can enter a "mapping mode" in which the App asks the user to put the sticks on 0% throttle, 100% throttle, left yaw, right yaw, roll, pitch... etc

This would cover any type of control preference at once.

**Comment by ghost** [comment]
After having a second look at the code I found that main.js is not used (yet ?)..
Editing build.js brought me "Mode 2" controls and normal throttle (can be found at my fork)

btw: I really hope that you can implement video stream. Would be awesome!

**Comment by FREEZX** [comment]
main.js is being built into build.js by using browserify and/or watchify, so we can have a more organized codebase.

**Comment by ghost** [comment]
ok
My friend and I tried joystick controlling it last week and it actually worked. The spring on the joystick is a bit awkward to work against, but all in all it's verry intuitive and fun.
Are you still planning on implementing video stream or did you run into a major issue? I didn't try the other guys C# code from reddit so I cant tell if the problem even theoretically is solved.
btw: the [reddit thread](https://www.reddit.com/r/HowToHack/comments/4512il/how_to_hack_ip_camera_in_toy_drone/) seems to be dead by now

**Comment by mir888** [comment]
Hello,
I have drone Cheerson cx10w wifi version, it can be controlled with app https://play.google.com/store/apps/details?id=com.gx_cx_10wifi
I wanted to be able to control this drone with my gamepad, I am using gamepad - https://www.tracer.pl/gamepad-tracer-shogun-trj-208-pc
I tested my Tracer gamepad here http://html5gamepad.com/ and everything was working.
When I installed your chrome app It didn't work with my gamepad Tracer.
When connected the binding LEDs of my drone stop flashing. 
But when I try to move the gamepad Tracer controller sticks and pressing all the buttons  noting happened.
Attaching chrome log info...
![1](https://cloud.githubusercontent.com/assets/22914885/23609510/0f105e20-0277-11e7-8326-4ecf4af853c1.png)

Do you have any idea what should be done your chrome app to work with my gamepad - https://www.tracer.pl/gamepad-tracer-shogun-trj-208-pc and drone Cheerson cx10w wifi version.

Thanks in advance,
Maria
