### ISSUE TITLE
Video

### ISSUE THREAD

**Issue by adrianlzt** [FREEZX/fq777-954-chrome-app#5]
Hi,

I show some code that seems to try to decode video. Do you achieve something?

Thanks

**Comment by FREEZX** [comment]
I might, i tried decoding video once, but something didn't work right.

**Comment by adrianlzt** [comment]
Do you have some code to obtain a frame or something.
I was reading the [reddit post](https://www.reddit.com/r/HowToHack/comments/4512il/how_to_hack_ip_camera_in_toy_drone/) but the download links are broken.

**Comment by FREEZX** [comment]
The whole video data is located here: 
https://github.com/FREEZX/fq777-954-chrome-app/blob/master/js/main.js#L204
I don't know anything about video frames or video decoding, but i was able to play this data with ffmpeg, Sample captured data can be found here https://github.com/FREEZX/fq777-954-chrome-app/raw/master/out.mp4.
My issue is playing this and more importantly, streaming it in the app.

**Comment by adrianlzt** [comment]
Ok, thanks. I'll take a look and come back if found something useful
